[package]
name = "pulldown-cmark"
version = "0.1.0"
authors = ["vratnam <vadhrivenkata.ratnam@nagra.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
pulldown-cmark = "0.7.0"
maud = "0.21.0"
failure = "0.1.7"
