[package]
name = "chatbox-lib"
version = "0.1.0"
authors = ["vratnam <vadhrivenkata.ratnam@nagra.com>"]
edition = "2018"

[dependencies]
futures = "0.3.4"
tokio = { version = "0.2", features = ["full"] }
tokio-channel = "0.1.0"
