[package]
name = "futures_channels"
version = "0.1.0"
authors = ["vratnam <vadhrivenkata.ratnam@nagra.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures="0.3.4"
futures-util = "0.3.4"
