  config:
    target: "ws://localhost:3030/ws"
    processor: "./wss-func/func.js"
    phases:
      - duration: 5
        arrivalRate: 100
  scenarios:
    - engine: "ws"
      flow:
        - function: "createTimestampedObject"
        - send: "{{ data }}"
